/**
 * Couche service - pdf.service.js
 * Contient la logique metier et centralise les appels aux modeles MongoDB.
 */
import PDFDocument from "pdfkit";

export const generatePDF = (documentData) => {
  const doc = new PDFDocument({
    margin: 50
  });
  const createdAt = documentData.createdAt ? new Date(documentData.createdAt) : new Date();
  const documentId = documentData.id || documentData._id || "n/a";
  const documentType = String(documentData.type || "").replaceAll("_", " ");

  doc.fontSize(18).font("Helvetica-Bold").text(documentData.title, { align: "center" });
  doc.moveDown();

  doc.fontSize(10).font("Helvetica").text(`Type: ${documentType}`, { align: "left" });
  doc.text(`Format: ${documentData.format || "pdf"}`, { align: "left" });
  doc.text(`Created: ${createdAt.toLocaleDateString()}`, { align: "left" });
  doc.moveDown();

  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown();

  doc.fontSize(12).font("Helvetica").text(documentData.content, {
    align: "left",
    width: 500,
    lineGap: 5
  });

  if (documentData.type === "cv" && documentData.targetPosition) {
    doc.moveDown();
    doc.fontSize(11).font("Helvetica-Bold").text("Target Position:", { align: "left" });
    doc.fontSize(11).font("Helvetica").text(documentData.targetPosition, { align: "left" });
  }

  if (documentData.type === "motivation_letter") {
    if (documentData.recipientCompany) {
      doc.moveDown();
      doc.fontSize(11).font("Helvetica-Bold").text("Recipient Company:", { align: "left" });
      doc.fontSize(11).font("Helvetica").text(documentData.recipientCompany, { align: "left" });
    }
  }

  if (documentData.type === "application_email") {
    doc.moveDown();
    if (documentData.subject) {
      doc.fontSize(11).font("Helvetica-Bold").text("Subject:", { align: "left" });
      doc.fontSize(11).font("Helvetica").text(documentData.subject, { align: "left" });
    }
  }

  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.fontSize(9).font("Helvetica").text(`Generated by SmartApply AI | Document ID: ${documentId}`, {
    align: "center",
    color: "#666"
  });

  return doc;
};

export const streamPDFToResponse = (doc, res, filename, statusCode = 200) => {
  res.status(statusCode);
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}.pdf"`);
  doc.pipe(res);
  doc.end();
};

